- name: Hello World Sample
  hosts: all
  tasks:
    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: "{{ scm_url }}"
        dest: "{{ project_path }}"
        version: main

