- name: Create File
  hosts: all
  become: yes

  tasks:
    - name: Touch file
      file:
        path: /home/back-dev/testFile
        state: touch
        owner: root
        group: root
        mode: '0644'
